Specify ZonedDateTime.toPlain{YearMonth,MonthDay}()
tc39/proposal-temporal pull request #1157
Opened 2020-11-07 00:49 UTC by ptomato

See: #569

2020-11-09 12:41 UTC, Ms2ger requested changes

2020-11-09 12:41 UTC, Ms2ger commented on spec/zoneddatetime.html
> +        1. Let _fields_ be ? ToTemporalDateFields(_temporalDateTime_, _fieldNames_).
You don't need to get the day; use ToTemporalYearMonthFields instead.

2020-11-09 12:41 UTC, Ms2ger commented on spec/zoneddatetime.html
> +        1. Let _fields_ be ? ToTemporalDateFields(_temporalDateTime_, _fieldNames_).
Likewise

2020-11-09 16:39 UTC, ptomato commented
Thanks. Made the same change to the polyfill as well.

2020-11-10 10:05 UTC, Ms2ger approved these changes

2020-11-10 10:05 UTC, merged