Add exports to package.json
tc39/proposal-temporal pull request #1499
Opened 2021-04-19 18:24 UTC by ptomato

Closes: #1464

2021-04-19 19:09 UTC, cjtenny approved these changes
:goal_net:

2021-04-19 19:13 UTC, ljharb commented
Note that adding this is a breaking change; the format you've used won't work in every node version, and I'm not sure why this improvement is needed given that the polyfill should theoretically be deprecated _very_ soon?

2021-04-19 19:14 UTC, ljharb requested changes

2021-04-19 19:14 UTC, ljharb commented on polyfill/package.json
> +  },
this is what would be needed if you wanted to actually support every node version:
```suggestion
  "exports": {
     ".": [
       {
        "import": "./lib/index.mjs",
        "default": "./dist/index.js"
       },
       "./dist/index.js"
     ]
  },
```

but note that this is still a breaking change unless these are the only two files included in the package (which i can see they aren't from the "browser" field above)

2021-04-19 21:20 UTC, ptomato commented
> Note that adding this is a breaking change; the format you've used won't work in every node version, and I'm not sure why this improvement is needed given that the polyfill should theoretically be deprecated _very_ soon? (arguably, should have been deprecated a month ago, per prior agreements)

I don't agree that that precludes changes to leave it in a good place, but I didn't realize this was a breaking change.

2021-04-19 21:20 UTC, closed without merging

2021-04-19 21:53 UTC, ljharb commented
@ptomato "leaving it in a good place" is fine within a reasonable timeframe, ofc - adding new features tho, breaking or otherwise, seems a bit out of scope of that.

2021-04-20 02:32 UTC, littledan commented
What's wrong with a breaking change on something at version 0.8?

2021-04-28 18:33 UTC, ptomato commented
Certainly breaking changes are fine at version 0.8, but once I realized this was breaking, it seemed like just churn without a clear benefit, unlike the other breaking changes we've had.