Normative: Add Temporal[@@toStringTag].
tc39/proposal-temporal pull request #1541
Opened 2021-06-17 08:26 UTC by Ms2ger

Fixes #1539.

2021-06-17 14:05 UTC, ljharb requested changes

2021-06-17 14:05 UTC, ljharb commented on spec/temporal.html
> +      <h1>Intl[ @@toStringTag ]</h1>
```suggestion
      <h1>Temporal [ @@toStringTag ]</h1>
```

2021-06-17 14:14 UTC, Ms2ger commented on spec/temporal.html
> +      <h1>Intl[ @@toStringTag ]</h1>
Doh.

2021-06-17 14:21 UTC, ljharb approved these changes

2021-06-17 16:29 UTC, ptomato approved these changes
I will mark this as "draft" so it's not accidentally merged before being presented to plenary.

2021-06-23 18:49 UTC, ptomato commented
If we go with Temporal.now[@@toStringTag] as discussed on #1539 then this PR will need to be updated.

2021-07-27 00:20 UTC, ptomato commented
I believe this is covered by the consensus achieved at the July 2021 TC39 meeting as part of the "Guidance on nested namespaces" item. I will add the updates to `Temporal.Now` as per that item and un-draft this.

2021-07-27 16:10 UTC, merged