Editorial: communicate infallable time zone ops
tc39/proposal-temporal pull request #1633
Opened 2021-07-12 23:44 UTC by jugglinmike

2021-07-12 23:46 UTC, ljharb requested changes
unless the completion record is introspected, a call to a non-predicate AO should always have a `?` or `!`.

2021-07-12 23:46 UTC, ljharb commented on spec/temporal.html
> +        1. Return SystemTimeZone().
```suggestion
        1. Return ! SystemTimeZone().
```

2021-07-12 23:46 UTC, ljharb commented on spec/temporal.html
> +          1. Let _timeZone_ be SystemTimeZone().
```suggestion
          1. Let _timeZone_ be ! SystemTimeZone().
```

2021-07-12 23:46 UTC, ljharb commented on spec/temporal.html
> +          1. Let _timeZone_ be SystemTimeZone().
```suggestion
          1. Let _timeZone_ be ! SystemTimeZone().
```

2021-07-13 18:31 UTC, ptomato commented
Thanks! My understanding of the notation matches Jordan's. Otherwise this looks correct.

2021-07-13 20:22 UTC, jugglinmike commented
@ptomato you got it. Bear in mind that [applying `!` in this way may not be supported by the editors](https://github.com/tc39/proposal-resizablearraybuffer/pull/62#issuecomment-877338412).

2021-07-13 20:30 UTC, ljharb commented
@jugglinmike before the planned "completion reform", applying it in this way is the rule. The editors aren't a fan, but so far have preferred consistency pending an overhaul of all AOs.

2021-07-13 22:37 UTC, ptomato commented
Like most things I've encountered in TC39, I wasn't aware there was a controversy about it. Nonetheless, being consistent until the editors provide guidance seems fine to me.

2021-07-13 22:39 UTC, ptomato approved these changes

2021-07-13 22:39 UTC, merged