Wrap _options
tc39/proposal-temporal pull request #1640
Opened 2021-07-14 05:36 UTC by FrankYFTang

2021-07-14 05:37 UTC, ljharb approved these changes

2021-07-14 05:41 UTC, FrankYFTang commented
try to fix https://github.com/tc39/proposal-temporal/issues/1639

2021-07-26 22:52 UTC, ptomato requested changes
This changes the value of the `length` property of the affected functions, could you modify the appropriate tests as well to reflect the new `length` value?

2021-07-26 22:52 UTC, ptomato commented on spec/duration.html
> +      <h1>Temporal.Duration.prototype.total ( [ _options_ ] )</h1>
This one is not optional because the `unit` is required. (Consider adding an `undefined` -> TypeError check in #1646?)

2021-07-27 00:11 UTC, ptomato commented
(Converting normative PR to draft so it is not accidentally merged without consensus)

2021-08-12 23:27 UTC, ptomato commented
I added tests to this, it should be ready to present for consensus now.

2021-08-12 23:46 UTC, ljharb approved these changes

2021-08-31 19:13 UTC, ptomato approved these changes

2021-08-31 19:13 UTC, ptomato commented
This change achieved consensus in TC39.

2021-08-31 19:13 UTC, merged