Editorial: document infallability of AO invocation
tc39/proposal-temporal pull request #1642
Opened 2021-07-14 17:52 UTC by jugglinmike

CreateTemporalCalendar cannot return an abrupt completion record when
invoked with a single parameter.

2021-07-14 17:55 UTC, ljharb approved these changes

2021-07-15 09:19 UTC, Ms2ger requested changes
I'm generally not convinced that OrdinaryCreateFromConstructor is infallible. If you are, could you share your reasoning?

2021-07-16 22:28 UTC, jugglinmike commented
@Ms2ger I'm generally not convinced of that, either. For the specific invocation in question, though, OrdinaryCreateFromConstructor can't return an abrupt completion because it's being called with a well-known intrinsic object that is a constructor.

2021-07-26 23:52 UTC, jugglinmike commented
@Ms2ger It's been a little while, so I'm commenting here to make sure this patch didn't slip off your radar.

2021-07-28 08:31 UTC, Ms2ger approved these changes
ok

2021-07-28 08:31 UTC, merged