Treat System Epoch in nanoseconds as bigint.BigInteger.
tc39/proposal-temporal pull request #1848
Opened 2021-09-25 02:51 UTC by 12wrigja

This is the same as https://github.com/js-temporal/temporal-polyfill/pull/58.

2021-09-25 17:53 UTC, justingrant requested changes
See https://github.com/js-temporal/temporal-polyfill/pull/58/files#r716075108

2021-09-27 22:25 UTC, 12wrigja commented
Updated with the outcome of the PR over in the js-temporal repo.

2021-09-27 23:14 UTC, justingrant approved these changes

2021-09-27 23:18 UTC, ptomato approved these changes
:+1:

2021-09-27 23:19 UTC, merged