Emit reference information when calendarName = 'always'
tc39/proposal-temporal pull request #2035
Opened 2022-02-04 07:55 UTC by jessealama

closes #1971

2022-02-04 20:59 UTC, ptomato commented
This needs a corresponding change in the spec text.

2022-02-07 12:52 UTC, jessealama commented
updated spec text

2022-02-07 20:25 UTC, ptomato requested changes

2022-02-07 20:25 UTC, ptomato commented on spec/plainmonthday.html
> +        1. If _showCalendar_ is not *"always"* or if _calendarID_ is not *"iso8601"*, then
```suggestion
        1. If _showCalendar_ is *"always"* or if _calendarID_ is not *"iso8601"*, then
```
?

2022-02-11 07:50 UTC, jessealama commented on spec/plainyearmonth.html
> +        1. If _showCalendar_ is not *"always" or if *_calendarID_ is not *"iso8601"*, then
quite right, thanks!

2022-02-11 08:18 UTC, jessealama commented on spec/plainyearmonth.html
> +        1. If _showCalendar_ is not *"always" or if *_calendarID_ is not *"iso8601"*, then
oops, yes -- done

2022-02-11 18:12 UTC, ptomato approved these changes
:+1:

Will keep this marked as a draft until presented at TC39.

2022-03-29 23:56 UTC, ptomato commented
This achieved consensus at the March 2022 TC39 plenary meeting.

2022-03-30 15:25 UTC, merged