Sync amendments to Intl-402
tc39/proposal-temporal pull request #3058
Opened 2024-12-09 13:26 UTC by anba

2024-12-09 22:07 UTC, ptomato requested changes
Thanks! I believe you missed a couple of name changes, otherwise looks good.

2024-12-09 22:07 UTC, ptomato commented on spec/intl.html
> +          1. Let _resultParts_ be FormatDateTimePattern(_dateTimeFormat_, _format_, _pattern_, _x_).
```suggestion
          1. Let _resultParts_ be FormatDateTimePattern(_dateTimeFormat_, _format_, _pattern_, _xEpochNanoseconds_).
```

2024-12-09 22:07 UTC, ptomato commented on spec/intl.html
>              1. Let _z_ be _y_.
```suggestion
            1. Let _z_ be _xEpochNanoseconds_.
          1. Else,
            1. Let _z_ be _yEpochNanoseconds_.
```

2025-01-16 20:13 UTC, ptomato commented on spec/intl.html
> -              1. <ins>Let _v_ be *undefined*.</ins>
I took another look at this today, with an eye to merging it. But I noticed that this change hasn't been incorporated upstream yet: https://tc39.es/ecma402/#sec-intl.datetimeformat.prototype.resolvedoptions
Could you take another look at it?

2025-01-17 09:43 UTC, anba commented on spec/intl.html
> -              1. <ins>Let _v_ be *undefined*.</ins>
This case is handled in [CreateDateTimeFormat](https://tc39.es/ecma402/#sec-createdatetimeformat), step 44:
> 44. If bestFormat has a field [[hour]], then
>        a. Set dateTimeFormat.[[HourCycle]] to hc.

Which means the Temporal change to remove that step needs to be removed.

2025-01-17 20:05 UTC, ptomato commented on spec/intl.html
> -              1. <ins>Let _v_ be *undefined*.</ins>
Got it. Thanks!

2025-01-17 20:06 UTC, ptomato approved these changes
Approving based on the above comments.

2025-01-17 20:06 UTC, merged